/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v11.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_401
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_rtc_1.h"

/*******************************************************************************
 * rtc_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'rtc_1'
- type: 'rtc_config'
- mode: 'rtcDriver'
- custom_name_enabled: 'false'
- type_id: 'rtc'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'RTC'
- config_sets:
  - rtc_driver:
    - rtcInitConfig:
      - 0:
        - init:
          - name: 'rtc_1InitCfg0'
          - readonly: 'true'
          - updateEnable: 'false'
          - nonSupervisorAccessEnable: 'true'
          - compensationEnable: 'false'
          - compensationInterval: '0'
          - compensation: '0'
          - clockSelect: 'RTC_CLK_SRC_LPO_1KHZ'
          - clockOutConfig: 'RTC_CLKOUT_DISABLED'
        - date:
          - 0:
            - year: '2025'
            - month: '7'
            - day: '28'
            - hour: '15'
            - minutes: '43'
            - seconds: '0'
    - rtcLockConfig:
      - 0:
        - enableCfg: 'true'
        - name: 'rtc_1LockCfg0'
        - readonly: 'true'
        - lockRegisterLock: 'false'
        - statusRegisterLock: 'false'
        - controlRegisterLock: 'false'
        - timeCompensationRegisterLock: 'false'
    - rtcAlarmConfig:
      - 0:
        - enableCfg: 'true'
        - name: 'rtc_1AlarmCfg0'
        - alarmTime:
          - 0:
            - year: '1970'
            - month: '1'
            - day: '1'
            - hour: '0'
            - minutes: '0'
            - seconds: '0'
        - repeat: 'false'
        - repeatForever: 'false'
        - repetitionInterval: '0'
        - numberOfRepeats: '0'
        - alarmIntEnable: 'false'
        - alarmCallback: 'NULL'
    - rtcTSIConfig:
      - 0:
        - enableCfg: 'true'
        - name: 'rtc_1SecIntCfg0'
        - secondIntConfig: 'RTC_INT_1HZ'
        - secondIntEnable: 'false'
        - rtcSecondsCallback: 'NULL'
    - rtcFaultConfig:
      - 0:
        - enableCfg: 'true'
        - name: 'rtc_1FaultCfg0'
        - overflowIntEnable: 'false'
        - timeInvalidIntEnable: 'false'
        - rtcCallback: 'NULL'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
*
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/*
 * RTC Initialization configurations
 */

/*! rtc_1InitCfg0 instance initialization configuration */
const rtc_init_config_t rtc_1InitCfg0 = {
  .updateEnable = false,
  .nonSupervisorAccessEnable = true,
  .compensationInterval = 0U,
  .compensation = 0,
  .clockSelect = RTC_CLK_SRC_LPO_1KHZ,
  .clockOutConfig = RTC_CLKOUT_DISABLED
};

/*! rtc_1InitCfg0_StartTime Initial Time and Date */
const rtc_timedate_t rtc_1InitCfg0_StartTime  = {
  .year = 2025U,
  .month = 7U,
  .day = 28U,
  .hour = 15U,
  .minutes = 43U,
  .seconds = 0U
};

/*
 * RTC Register Lock configurations
 */

/*! rtc_1LockCfg0 register lock configuration */
const rtc_register_lock_config_t rtc_1LockCfg0 = {
  .lockRegisterLock = false,
  .statusRegisterLock = false,
  .controlRegisterLock = false,
  .timeCompensationRegisterLock = false
};

/*
 * RTC Alarm configurations
 */

/*! rtc_1AlarmCfg0 alarm configuration */
rtc_alarm_config_t rtc_1AlarmCfg0 = {
  .alarmTime = {
    .year = 1970U,
    .month = 1U,
    .day = 1U,
    .hour = 0U,
    .minutes = 0U,
    .seconds = 0U
  },
  .repeatForever = false,
  .repetitionInterval = 0UL,
  .numberOfRepeats = 0UL,
  .alarmIntEnable = false,
  .callbackParams = NULL,
  .alarmCallback = NULL
};

/*
 * RTC Time Seconds Interrupt configurations
 */

/*! rtc_1SecIntCfg0 time seconds configuration */
rtc_seconds_int_config_t rtc_1SecIntCfg0 = {
  .secondIntConfig = RTC_INT_1HZ,
  .secondIntEnable = false,
  .secondsCallbackParams = NULL,
  .rtcSecondsCallback = NULL
};

/*
 * RTC Fault interrupt configurations
 */

/*! rtc_1FaultCfg0 fault configuration */
rtc_interrupt_config_t rtc_1FaultCfg0 = {
  .overflowIntEnable = false,
  .timeInvalidIntEnable = false,
  .callbackParams = NULL,
  .rtcCallback = NULL
};


