/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v11.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_401
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_pdb_config_1.h"

/*******************************************************************************
 * pdb_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'pdb_config_1'
- type: 'pdb'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'pdb'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PDB_0'
- config_sets:
  - pdb_driver:
    - adcTrigCfgs:
      - 0:
        - name: 'pdb_config_1_adcTrigConfig0'
        - readOnly: 'true'
        - adcPreTriggerIdx: '0'
        - preTriggerEnable: 'true'
        - preTriggerOutputEnable: 'true'
        - preTriggerBackToBackEnable: 'false'
      - 1:
        - name: 'pdb_config_1_adcTrigConfig1'
        - readOnly: 'true'
        - adcPreTriggerIdx: '1'
        - preTriggerEnable: 'true'
        - preTriggerOutputEnable: 'true'
        - preTriggerBackToBackEnable: 'true'
      - 2:
        - name: 'pdb_config_1_adcTrigConfig2'
        - readOnly: 'true'
        - adcPreTriggerIdx: '2'
        - preTriggerEnable: 'true'
        - preTriggerOutputEnable: 'true'
        - preTriggerBackToBackEnable: 'true'
    - pdbCfgs:
      - 0:
        - name: 'pdb_config_1_timerConfig0'
        - readOnly: 'true'
        - loadValueMode: 'PDB_LOAD_VAL_IMMEDIATELY'
        - seqErrIntEnable: 'false'
        - clkPreDiv: 'PDB_CLK_PREDIV_BY_1'
        - clkPreMultFactor: 'PDB_CLK_PREMULT_FACT_AS_1'
        - triggerInput: 'PDB_TRIGGER_IN0'
        - continuousModeEnable: 'false'
        - dmaEnable: 'true'
        - intEnable: 'false'
        - instanceBackToBackEnable: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/*! @brief ADC pre-trigger configurations */
const pdb_adc_pretrigger_config_t pdb_config_1_adcTrigConfig0 = {
    .adcPreTriggerIdx = 0U,
    .preTriggerEnable = true,
    .preTriggerOutputEnable = true,
    .preTriggerBackToBackEnable = false
};

const pdb_adc_pretrigger_config_t pdb_config_1_adcTrigConfig1 = {
    .adcPreTriggerIdx = 1U,
    .preTriggerEnable = true,
    .preTriggerOutputEnable = true,
    .preTriggerBackToBackEnable = true
};

const pdb_adc_pretrigger_config_t pdb_config_1_adcTrigConfig2 = {
    .adcPreTriggerIdx = 2U,
    .preTriggerEnable = true,
    .preTriggerOutputEnable = true,
    .preTriggerBackToBackEnable = true
};


/*! @brief PDB timer configurations */
const pdb_timer_config_t pdb_config_1_timerConfig0 = {
    .loadValueMode = PDB_LOAD_VAL_IMMEDIATELY,
    .seqErrIntEnable = false,
    .clkPreDiv = PDB_CLK_PREDIV_BY_1,
    .clkPreMultFactor = PDB_CLK_PREMULT_FACT_AS_1,
    .triggerInput = PDB_TRIGGER_IN0,
    .continuousModeEnable = false,
    .dmaEnable = true,
    .intEnable = false,
    .instanceBackToBackEnable = false,
};



