/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef rtc_1_H
#define rtc_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
*
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 8.5, object/function previously declared
 * It is safe, because the file has include guards to prevent multiple declarations of the same object/function.
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "rtc_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/

/* Device instance number */
#define RTC_1  (0U)

/*******************************************************************************
 * Global variables 
 ******************************************************************************/

/*
 * RTC Initialization configurations
 */

/* User configuration 0 */
extern const rtc_init_config_t rtc_1InitCfg0;
extern const rtc_timedate_t rtc_1InitCfg0_StartTime;

/*
 * RTC Register Lock configurations
 */

/* Register Lock configuration 0 */
extern const rtc_register_lock_config_t rtc_1LockCfg0;

/*
 * RTC Alarm configurations
 */

/* Alarm configuration 0 */
extern rtc_alarm_config_t rtc_1AlarmCfg0;

/*
 * RTC Time Seconds Interrupt configurations
 */

/* Time Seconds Interrupt configuration 0 */
extern rtc_seconds_int_config_t rtc_1SecIntCfg0;

/*
 * RTC Fault interrupt configurations
 */

/* Fault interrupt configuration 0 */
extern rtc_interrupt_config_t rtc_1FaultCfg0;



#endif /* rtc_1_H */
